# Generated by Django 5.2.6 on 2025-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, default='fuck you', null=True)),
                ('subject', models.CharField(default='fuck you', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
