# Generated by Django 5.2.6 on 2025-09-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sentmodel',
            name='subject',
        ),
    ]
